
此文档的主要作用为记录机器学习平台开发中出现的bug，及解决方法：

2017-12-06 发现如下bug 需要解决

1.raise ValueError('Unknown element o')
发生位置 绘制auc ks曲线图时发生

解决方法：去modelutil中的plot_roc_line函数中加入try except
原因分析：猜想是linux下matlib的font原因导致的，主要原因可能是图中有中文的问题

2.TypeError: Object of type int64 is not JSON serializable
发生位置 f_type1Output 中 序列化对象时发生

解决办法 ： try except 如果是TypeError 就去一一处理，这一次是避免int64类型数据的出现
解决时发现 这是个非常顽固的bug

解决bug的记录：
x = np.array([1, 2, 3], dtype=np.int64)
    x
    x.dtype
    y = x.astype(np.int32)
    y
    z = [1, 2, 3]

    xx = pd.DataFrame(x, columns=['x']).to_dict(orient='records')
    yy = pd.DataFrame(y, columns=['y']).to_dict(orient='records')
    zz = pd.DataFrame({"z1": z, "z2": z})
    zz.dtypes
    zz.z1 = zz.z1.apply(np.int)
    zz.z2 = zz.z2.apply(np.int)
    zzz = zz.to_dict(orient='records')
    zzz

    simplejson.dumps({'xx': xx}, ensure_ascii=False, ignore_nan=True)
    simplejson.dumps({'yy': yy}, ensure_ascii=False, ignore_nan=True)
    simplejson.dumps(zzz, ensure_ascii=False, ignore_nan=True)
    import json
    json.dumps(zzz, ensure_ascii=False, cls=MyEncoder)

    # 经发现 DataFrame中的int 都不能转为json 真的是奇怪了啊


import json

#https://stackoverflow.com/questions/27050108/convert-numpy-type-to-python/27050186#27050186
class MyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)




3.在异步的线程中，如果出错，也要回调，回调内容为，请求ID，错误的大致内容，状态码 502

4.在大的计算函数上，加入错误日志的装饰器函数


5.2017-12-04 发现
 UserWarning: Multiprocessing backed parallel loops cannot be nested below threads, setting n_jobs=1

 随机森林出现的问题


6.2017-12-21 发现

在弄建模大赛的数据时 出现了bug
service abrtd status
systemctl stop abrtd

bug原因，在跑GBM时，触发了系统的什么东西 导致了将服务杀死

Dec 21 18:05:55 datasvr6017 abrt-server[107804]: Executable '/home/anaconda3/bin/python3.6' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Dec 21 18:05:55 datasvr6017 abrt-server[107804]: 'post-create' on '/var/spool/abrt/ccpp-2017-12-21-18:05:49-106810' exited with 1
Dec 21 18:05:55 datasvr6017 abrt-server[107804]: Deleting problem directory '/var/spool/abrt/ccpp-2017-12-21-18:05:49-106810'

[root@datasvr6017 CcxMLOGE-0.1.0]# cat /var/log/dmesg |grep 'kill'
[root@datasvr6017 CcxMLOGE-0.1.0]# cat /var/log/messages |grep 'kill'
Dec 21 17:11:21 datasvr6017 abrt-hook-ccpp: Process 178683 (python3.6) of user 0 killed by SIGSEGV - dumping core
Dec 21 17:24:01 datasvr6017 abrt-hook-ccpp: Process 104342 (python3.6) of user 0 killed by SIGSEGV - dumping core
Dec 21 17:31:20 datasvr6017 abrt-hook-ccpp: Process 105017 (python3.6) of user 0 killed by SIGSEGV - dumping core
Dec 21 17:39:39 datasvr6017 abrt-hook-ccpp: Process 105305 (python3.6) of user 0 killed by SIGSEGV - dumping core
Dec 21 18:05:49 datasvr6017 abrt-hook-ccpp: Process 106810 (python3.6) of user 0 killed by SIGSEGV - dumping core

#此bug 暂未解决 解决思路：更换lightgbm的版本

7.2017-12-25 时发现bug
bug1: File "/home/anaconda3/lib/python3.6/site-packages/ccxmodel/modelmain.py", line 139, in ccxboost_main
    param, num_round = Model.get_bstpram(re)
bug分析：由于数据量较小 出现了惩罚因子较大，导致的被零除的错误

File "/home/anaconda3/lib/python3.6/site-packages/ccxmodel/modelmain.py", line 87, in ccxrf_main
    trks_path = MU.plot_ks_line(train[y_colnames], train_pred_y, title=cv_mess + '_train_ks-Curve')
  File "/home/anaconda3/lib/python3.6/site-packages/ccxmodel/modelutil.py", line 109, in plot_ks_line
    plt.xticks(np.arange(0, len(tpr), len(tpr) // 10), np.arange(0, 1.1, 0.1))
ZeroDivisionError: division by zero

bug分析：同理 在画图时 也出现了类似的错误

bug解决思路：重新一次获取最优参数的函数 使其更为健全，画图的语句，用try catch 包住


2018-01-08 王超跑模型时出现了两个bug
1.读取数据时的文件编码问题 inputTransform模块新增了函数 f_ReadData解决
2.概率分箱时的问题 outputTransform模块565行至576新增了判断语句解决


2018-01-13 发现了100.175引入matplotlib.pyplot 时 发现的bug
bug：
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
#查阅后的解决命令
yum install mesa-libGL.x86_64
#发现bug发生了改变
ImportError: /lib64/libGL.so.1: undefined symbol: drmFreeDevice
#最后使用了如下命令得以解决
yum update
#有效


2018-01-14 再测试遗传算法制造特征工程时 出现bug
#bug原因未找到，1,后台进程还在，也接收到前端的请求了，但是没有往下运行
#2.另外一个bug就是 ValueError: I/O operation on closed file.
#第二个bug的原因是，在with语句中，把控制台的重定向给关闭了，但是这个bug之前已经修改了，按理不应该出现了才对


2018-01-24 至小信用部署时发现的最大的bug
一跑lightgbm，后台的进程就会死去。未找到原因
一点点bug线索：
type=ANOM_ABEND msg=audit(1516775306.071:3106): auid=3002 uid=0 gid=0 ses=236 pid=30046 comm="python" reason="memory violation" sig=11